### ISSUE TITLE
liblua5.1.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by probonopd** [free-easy/DeviceInterface#1]
Getting `/tmp/.mount_Device5BWvNf/usr/bin/DeviceInterface: error while loading shared libraries: liblua5.1.so.0: cannot open shared object file: No such file or directory` when trying to run this on openSUSE LEAP 42.2.

How was the AppImage generated? `linuxdeployqt` should normally take care of this...

**Comment by chenlijun99** [comment]
@probonopd  Thank you very much for reporting this error!
I've edited the release and now it should work.
You can try to re-download the appimage and execute it!

TL;DR
I generated the AppImage manually with `appimagetool`.

The AppDir structure was like so:
```sh
├── AppRun
├── DeviceInterface.desktop
├── DeviceInterface.png
└── usr
    ├── bin
    ├── lib
    └── plugins
```
and the content of AppRun was 
```sh
#!/bin/sh
HERE=$(dirname $(readlink -f "${0}"))
LD_LIBRARY_PATH="${HERE}/usr/lib:$LD_LIBRARY_PATH"
LD_LIBRARY_PATH="${HERE}/usr/plugins/xcbglintegrations/:$LD_LIBRARY_PATH"
LD_LIBRARY_PATH="${HERE}/usr/plugins/imageformats/:$LD_LIBRARY_PATH"
LD_LIBRARY_PATH="${HERE}/usr/plugins/platforms/:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH
"${HERE}/usr/bin/DeviceInterface" "$@"
```
I first ran `linuxdeployqt` with my executable as argument and got `lib` and `plugins` directories.
Then I copied them to `AppDir/usr/` and there I used this command
`$ ldd ./bin/DeviceInterface | awk '{ print $3 }' | xargs -n1 -I{} cp {} ./lib`
because I thought that `linuxdeployqt` would just deal with Qt libraries and all the other libraries would have to be copied in separately.  
I didn't even notice that in the `lib` directory there were already all the necessary libraries... I'm so heedless

But now, by reading the documentation of `linuxdeployqt` more accurately and following your example in the wiki, I've realize that it was way simpler than I thought.
I've re-generated the appimage with following AppDir
```

├── DeviceInterface.desktop
├── DeviceInterface.png
└── usr
    └── bin
        └── DeviceInterface
```
I just ran `linuxdeployqt usr/bin/DeviceInterface` and everything was Ok! Easy!

Finally thank you again for reporting this issue and most of all thank you for the awesome `linuxdeployqt`.
